### ISSUE TITLE
Create a JS Game object

### ISSUE THREAD

**Issue by jncormier24** [OctopodGames/Rodents-Revenge#12]
Someone will need to create the functions for the Game object in the object_model.js.

**Comment by ghost** [comment]
Hey Joe & ZachD,
I made some stubs for the Game object. I don't know if they are what you are looking for exactly, though. Should I put in the push request anyway, or would you rather take a look at the changes first? They are at 
https://github.com/lkrenitsky/Rodents-Revenge/blob/develop/js/object_model.js

**Comment by jncormier24** [comment]
This is a good start. We came up with some ideas for the different functions we'd need for each object and you pretty much nailed the idea. I should point out that the Game variable above your Game function is where the game object will be. Doing it that way will allow us to create the objects much easier. 

For now, you don't need to push, you can just keep coding.

**Comment by zbtirrell** [comment]
I'd push.  This will give others a place to contribute and merge in their items.
