### ISSUE TITLE
Create JS object structure

### ISSUE THREAD

**Issue by zbtirrell** [OctopodGames/Rodents-Revenge#2]
We need the object structure with stub functions defined.  Once that is put together, we need tickets to be able to assign to others to build out and test each function.

**Comment by Camwyn** [comment]
Basic objects are designed - based off the in-class work. All objects on the board take (x,y) coordinates for init and the board object contains an array (board.squares) that can be used to check for collisions (empty squares return null).

**Comment by Camwyn** [comment]
So I think our object creation is faulty. I'm fixing but won't be able to commit until this evening.

Essentially, we keep recreating the same object. Overriding its properties each time. Thus, looping through cats to move each only moves the last created.

**Comment by zcdziura** [comment]
I'm working on the object structure right now, as well. I saw the same problem and will (hopefully) fix it. It may require a bit of rewriting to some parts, but core functionality (and more importantly, all the hard work everyone's been doing) will not be deleted.

**Comment by Camwyn** [comment]
Putting what I was doing on hold in deference to Zach...
